yolo_model:

  config_file:
    name: yolov4_billiard.cfg
  weight_file:
    name: yolov4_billiard.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - '0'
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
      - '6'
      - '7'
      - '8'
      - '9'
      - '10'
      - '11'
      - '12'
      - '13'
      - '14'
      - '15'
