yolo_model:

  config_file:
    name: yolov4_classification.cfg
  weight_file:
    name: yolov4_classification.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - metal
      - plastic
      - paper
